// This file was generated by counterfeiter
package mock

import (
	"io"
	"sync"

	"github.com/c0-ops/goblob"
)

type FakeStore struct {
	NameStub        func() string
	nameMutex       sync.RWMutex
	nameArgsForCall []struct{}
	nameReturns     struct {
		result1 string
	}
	ListStub        func() ([]*goblob.Blob, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct{}
	listReturns     struct {
		result1 []*goblob.Blob
		result2 error
	}
	ReadStub        func(src *goblob.Blob) (io.ReadCloser, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct {
		src *goblob.Blob
	}
	readReturns struct {
		result1 io.ReadCloser
		result2 error
	}
	ChecksumStub        func(src *goblob.Blob) (string, error)
	checksumMutex       sync.RWMutex
	checksumArgsForCall []struct {
		src *goblob.Blob
	}
	checksumReturns struct {
		result1 string
		result2 error
	}
	WriteStub        func(dst *goblob.Blob, src io.Reader) error
	writeMutex       sync.RWMutex
	writeArgsForCall []struct {
		dst *goblob.Blob
		src io.Reader
	}
	writeReturns struct {
		result1 error
	}
	ExistsStub        func(*goblob.Blob) bool
	existsMutex       sync.RWMutex
	existsArgsForCall []struct {
		arg1 *goblob.Blob
	}
	existsReturns struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) Name() string {
	fake.nameMutex.Lock()
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct{}{})
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if fake.NameStub != nil {
		return fake.NameStub()
	} else {
		return fake.nameReturns.result1
	}
}

func (fake *FakeStore) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeStore) NameReturns(result1 string) {
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeStore) List() ([]*goblob.Blob, error) {
	fake.listMutex.Lock()
	fake.listArgsForCall = append(fake.listArgsForCall, struct{}{})
	fake.recordInvocation("List", []interface{}{})
	fake.listMutex.Unlock()
	if fake.ListStub != nil {
		return fake.ListStub()
	} else {
		return fake.listReturns.result1, fake.listReturns.result2
	}
}

func (fake *FakeStore) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeStore) ListReturns(result1 []*goblob.Blob, result2 error) {
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []*goblob.Blob
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Read(src *goblob.Blob) (io.ReadCloser, error) {
	fake.readMutex.Lock()
	fake.readArgsForCall = append(fake.readArgsForCall, struct {
		src *goblob.Blob
	}{src})
	fake.recordInvocation("Read", []interface{}{src})
	fake.readMutex.Unlock()
	if fake.ReadStub != nil {
		return fake.ReadStub(src)
	} else {
		return fake.readReturns.result1, fake.readReturns.result2
	}
}

func (fake *FakeStore) ReadCallCount() int {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return len(fake.readArgsForCall)
}

func (fake *FakeStore) ReadArgsForCall(i int) *goblob.Blob {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return fake.readArgsForCall[i].src
}

func (fake *FakeStore) ReadReturns(result1 io.ReadCloser, result2 error) {
	fake.ReadStub = nil
	fake.readReturns = struct {
		result1 io.ReadCloser
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Checksum(src *goblob.Blob) (string, error) {
	fake.checksumMutex.Lock()
	fake.checksumArgsForCall = append(fake.checksumArgsForCall, struct {
		src *goblob.Blob
	}{src})
	fake.recordInvocation("Checksum", []interface{}{src})
	fake.checksumMutex.Unlock()
	if fake.ChecksumStub != nil {
		return fake.ChecksumStub(src)
	} else {
		return fake.checksumReturns.result1, fake.checksumReturns.result2
	}
}

func (fake *FakeStore) ChecksumCallCount() int {
	fake.checksumMutex.RLock()
	defer fake.checksumMutex.RUnlock()
	return len(fake.checksumArgsForCall)
}

func (fake *FakeStore) ChecksumArgsForCall(i int) *goblob.Blob {
	fake.checksumMutex.RLock()
	defer fake.checksumMutex.RUnlock()
	return fake.checksumArgsForCall[i].src
}

func (fake *FakeStore) ChecksumReturns(result1 string, result2 error) {
	fake.ChecksumStub = nil
	fake.checksumReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Write(dst *goblob.Blob, src io.Reader) error {
	fake.writeMutex.Lock()
	fake.writeArgsForCall = append(fake.writeArgsForCall, struct {
		dst *goblob.Blob
		src io.Reader
	}{dst, src})
	fake.recordInvocation("Write", []interface{}{dst, src})
	fake.writeMutex.Unlock()
	if fake.WriteStub != nil {
		return fake.WriteStub(dst, src)
	} else {
		return fake.writeReturns.result1
	}
}

func (fake *FakeStore) WriteCallCount() int {
	fake.writeMutex.RLock()
	defer fake.writeMutex.RUnlock()
	return len(fake.writeArgsForCall)
}

func (fake *FakeStore) WriteArgsForCall(i int) (*goblob.Blob, io.Reader) {
	fake.writeMutex.RLock()
	defer fake.writeMutex.RUnlock()
	return fake.writeArgsForCall[i].dst, fake.writeArgsForCall[i].src
}

func (fake *FakeStore) WriteReturns(result1 error) {
	fake.WriteStub = nil
	fake.writeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) Exists(arg1 *goblob.Blob) bool {
	fake.existsMutex.Lock()
	fake.existsArgsForCall = append(fake.existsArgsForCall, struct {
		arg1 *goblob.Blob
	}{arg1})
	fake.recordInvocation("Exists", []interface{}{arg1})
	fake.existsMutex.Unlock()
	if fake.ExistsStub != nil {
		return fake.ExistsStub(arg1)
	} else {
		return fake.existsReturns.result1
	}
}

func (fake *FakeStore) ExistsCallCount() int {
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	return len(fake.existsArgsForCall)
}

func (fake *FakeStore) ExistsArgsForCall(i int) *goblob.Blob {
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	return fake.existsArgsForCall[i].arg1
}

func (fake *FakeStore) ExistsReturns(result1 bool) {
	fake.ExistsStub = nil
	fake.existsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	fake.checksumMutex.RLock()
	defer fake.checksumMutex.RUnlock()
	fake.writeMutex.RLock()
	defer fake.writeMutex.RUnlock()
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ goblob.Store = new(FakeStore)
