// This file was generated by counterfeiter
package goblobfakes

import (
	"sync"

	"github.com/c0-ops/goblob"
)

type FakeBlobMigrator struct {
	MigrateStub        func(blob *goblob.Blob) error
	migrateMutex       sync.RWMutex
	migrateArgsForCall []struct {
		blob *goblob.Blob
	}
	migrateReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBlobMigrator) Migrate(blob *goblob.Blob) error {
	fake.migrateMutex.Lock()
	fake.migrateArgsForCall = append(fake.migrateArgsForCall, struct {
		blob *goblob.Blob
	}{blob})
	fake.recordInvocation("Migrate", []interface{}{blob})
	fake.migrateMutex.Unlock()
	if fake.MigrateStub != nil {
		return fake.MigrateStub(blob)
	} else {
		return fake.migrateReturns.result1
	}
}

func (fake *FakeBlobMigrator) MigrateCallCount() int {
	fake.migrateMutex.RLock()
	defer fake.migrateMutex.RUnlock()
	return len(fake.migrateArgsForCall)
}

func (fake *FakeBlobMigrator) MigrateArgsForCall(i int) *goblob.Blob {
	fake.migrateMutex.RLock()
	defer fake.migrateMutex.RUnlock()
	return fake.migrateArgsForCall[i].blob
}

func (fake *FakeBlobMigrator) MigrateReturns(result1 error) {
	fake.MigrateStub = nil
	fake.migrateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBlobMigrator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.migrateMutex.RLock()
	defer fake.migrateMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeBlobMigrator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ goblob.BlobMigrator = new(FakeBlobMigrator)
